# Generated by Django 5.0.7 on 2024-07-17 13:23

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="check_periodicity",
            field=models.IntegerField(default=0,
                                      verbose_name="проверка периодичности"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.IntegerField(
                default=3, verbose_name="периодичность напоминания в днях"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="start_time",
            field=models.TimeField(
                blank=True,
                default=datetime.time(16, 23, 28, 576843),
                null=True,
                verbose_name="Время начала выполнения",
            ),
        ),
    ]
