# Generated by Django 5.0.7 on 2024-07-17 20:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits",
         "0003_habit_check_periodicity_alter_habit_periodicity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="start_time",
            field=models.TimeField(
                blank=True,
                default=datetime.time(23, 19, 40, 39741),
                null=True,
                verbose_name="Время начала выполнения",
            ),
        ),
    ]
